name: Publish to GitHub NPM Registry
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://npm.pkg.github.com'
      - name: Install dependencies
        run: npm install
      - name: Install Angular CLI
        run: npm install -g @angular/cli > /dev/null
      - name: Install library dependencies
        working-directory: ./projects/ngx-globus-sdk
        run: npm install
      - name: Build library
        run: ng build ngx-globus-sdk
      - name: Publish package on NPM
        working-directory: ./dist/ngx-globus-sdk
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}